#pragma once
#include <iostream>
#include <cassert>
#include <unordered_map>
#include <string_view>
#include <array>
#include <vector>
#include <math.h>    
#include <cmath>
#include <memory>
#include "DxLib.h"
#include "EffekseerForDXLib.h"
#include "Input.h"
#include "Camera.h"
#include "BaseObject.h"
#include "BaseChara.h"
#include "BaseScene.h"
#include "Field.h"
#include "Map.h"
#include "HitCheck.h"
#include "CollisionManager.h"
#include "Player.h"
#include "PlayerManager.h"
#include "CoinObject.h"
#include "ObjectManager.h"
#include "Game.h"
#include "SceneManager.h"